name: Basic build

on:
  push:
    branches:
      - 'master'
      - 'release/*'
  pull_request:
    branches:
      - 'master'
      - 'release/*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./api/src/FinancialHub/
      run: dotnet restore
    - name: Build
      working-directory: ./api/src/FinancialHub/
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./api/src/FinancialHub/
      run: dotnet test --no-build --verbosity normal
   
