name: SonarCloud analysis

on:
  push:
    branches: 
      - 'main'
    paths:
      - '*' 
      - '**'
  pull_request:
    branches: 
      - 'release/**'
    paths:
      - '*' 
      - '**'
      #TODO: add for api
  workflow_dispatch:
  
permissions:
    pull-requests: read

jobs:
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: './api/src/FinancialHub/FinancialHub.WebApi/'
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: './api/src/FinancialHub/FinancialHub.WebApi/'
        
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: api/src/FinancialHub/
          args:  
            -Dsonar.projectKey=chingling-152_my-financial-hub
            -Dsonar.organization=chingling-152
